web:
  assets:
    - id: bootstrap-css
      type: Css
#     path: https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css
      path: https://camino-planner.s3.ap-southeast-2.amazonaws.com/static/css/bootstrap-dc.css
    - id: camino-css
      type: Css
      path: https://camino-planner.s3.ap-southeast-2.amazonaws.com/static/css/camino.css
    - id: icons
      type: Directory
      path: https://camino-planner.s3.ap-southeast-2.amazonaws.com/icons
    - id: "Camino Icons"
      type: Font
      path: https://camino-planner.s3.ap-southeast-2.amazonaws.com/fonts/Camino-Icons.woff
