web:
  assets:
    - id: caminoCss
      type: Css
      path: camino.css
    - id: icons
      type: Directory
      path: ../icons
    - id: "Camino Icons"
      type: Font
      path: ../fonts/Camino-Icons.woff
  links:
    - id: helpLink
      type: Header
      links:
        - locale: ""
          label: Help
          path: "help-en.html"
