web:
  assets:
    - id: caminoCss
      type: Css
      path: https://camino-planner.s3.ap-southeast-2.amazonaws.com/static/camino.css
    - id: icons
      type: Directory
      path: https://camino-planner.s3.ap-southeast-2.amazonaws.com/icons
    - id: "Camino Icons"
      type: Font
      path: https://camino-planner.s3.ap-southeast-2.amazonaws.com/fonts/Camino-Icons.woff
  links:
    - id: helpLink
      type: Header
      links:
        - locale: ""
          label: Help
          path: "https://camino-planner.s3.ap-southeast-2.amazonaws.com/static/help-en.html"
