web:
  assets:
    jQueryJs: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js
    bootstrapCss: https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css
    bootstrapJs: https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js
  icons:
    #      base: https://camino-planner.s3.ap-southeast-2.amazonaws.com/icons
    base: ../icons
  fonts:
    #      base: https://camino-planner.s3.ap-southeast-2.amazonaws.com/fonts
    base: ../fonts
  map:
    tiles: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    #tiles: http://mt0.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}
