- name: Ensure nginx is installed
  yum:
    name: "{{ nginx_package_name }}"
    state: present

- name: Set up nginx configuration
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
