# A skeleton inventory, suitable for installing on an AWS ec2/lightsail instance
webservers:
  hosts:
    _HOST_
  vars:
    acme_account_email: _CONTACT_EMAIL_
    ansible_user: ec2-user
    ansible_ssh_private_key_file: _PATH_TO_PEM_
    force_certificate: false
    server_name: _HOST_
